### ISSUE TITLE
Carte lissée indicateur issue d'une division

### ISSUE THREAD

**Issue by ydidees** [riatelab/potential#2]
Bonjour,

J'aimerais utiliser le package _Potential_ pour faire une carte lissée d'un indicateur issu d'une division (par exemple densité de la population). Dans ce cas, il me semble (mais je me trompe peut-être) qu'on n'est pas censé faire le lissage directement sur l'indicateur en question, mais distinguer le numérateur et le dénominateur, en lissant l'un puis l'autre et en combinant les deux à la fin.
Comment est-il possible de coder cela avec la fonction "mcpotential" ou "potential" ?

Merci !

**Comment by rCarto** [comment]
Bonjour, 
Une [vignette](https://riatelab.github.io/potential/articles/web_only/exemple.html) propose un exemple de calcul de numérateur/dénominateur/combinaison.
L'argument `var` des fonctions `potential()` et `mcpotential()` accepte plusieurs variables.

**Comment by ydidees** [comment]
Super, merci beaucoup !!
